CREATE TABLE IF NOT EXISTS minions (
	id SERIAL PRIMARY KEY,
	name VARCHAR(30),
	age INT
);


CREATE TABLE IF NOT EXISTS mini1ons (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(30),
	age INT
);


CREATE TABLE IF NOT EXISTS mini2onss (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(30),
	age INT
);


DROP TABLE mini1ons
;

DROP TABLE mini2onss
;


ALTER TABLE minions
RENAME TO minions_info
;


ALTER TABLE minions_info
ADD COLUMN code CHAR(4),
ADD COLUMN task TEXT,
ADD COLUMN salary DECIMAL(8, 2)
;


ALTER TABLE minions_info
RENAME COLUMN salary TO banana
;


ALTER TABLE minions_info
ADD COLUMN email VARCHAR(20),
ADD COLUMN equipped BOOLEAN NOT NULL
;

CREATE TYPE type_mood 
AS ENUM (
	'happy',
	'relaxed',
	'stressed',
	'sad'
);

ALTER TABLE minions_info
ADD COLUMN mood type_mood
;

ALTER TABLE minions_info
ALTER COLUMN age SET DEFAULT 0,
ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "code" SET DEFAULT ''
;

-- ALTER TABLE minions_info
-- ADD CONSTRAINT UQ_id_email  
-- UNIQUE (id, email)

ALTER TABLE minions_info
ADD CONSTRAINT unique_containt
UNIQUE (id, email)
;

-- ADD CONSTRAINT CK_banana_is_positive

ALTER TABLE minions_info
ADD CONSTRAINT banana_check
CHECK (banana > 0)
;


ALTER TABLE minions_info
ALTER COLUMN task TYPE VARCHAR(150)
;


ALTER TABLE minions_info
ALTER COLUMN equipped
DROP NOT NULL
;


ALTER TABLE minions_info
DROP COLUMN age
;

CREATE TABLE minions_birthdays (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	date_of_birth DATE,
	age INT NOT NULL,
	present VARCHAR(100),
	party TIMESTAMPTZ
);


INSERT INTO 
	minions_info(name, code, task, banana, email, equipped, mood)
VALUES 
	('Mark', 'GKYA', 'Graphing Points', 3265.265, 'mark@minion.com', false, 'happy'),
	('Mel', 'HSK', 'Science Investigation', 54784.996, 'mel@minion.com', true, 'stressed'),
	('Bob', 'HF', 'Painting', 35.652, 'bob@minion.com', true, 'happy'),
	('Darwin', 'EHND', 'Create a Digital Greeting', 321.958, 'darwin@minion.com', false, 'relaxed'),
	('Kevin', 'KMHD', 'Construct with Virtual Blocks', 35214.789, 'kevin@minion.com', false, 'happy'),
	('Norbert', 'FEWB', 'Testing', 3265.500, 'norbert@minion.com', true, 'sad'),
	('Donny', 'L', 'Make a Map', 8.452, 'donny@minion.com', true, 'happy');


SELECT
	name,
	task,
	email, 
	banana
FROM
	minions_info
;


-- DELETE FROM minions_info
-- WHERE name = 'Mark';


TRUNCATE TABLE minions_info
;

DROP TABLE minions_birthdays
;


DROP DATABASE minions_db WITH (FORCE);
--this will be executed but if the command is run in another database


CREATE TYPE address AS (
	street VARCHAR(50),
	city VARCHAR(50),
	postal_code CHAR(4)
);

CREATE TABLE customers (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_name VARCHAR(100),
	customer_address address
);

INSERT INTO 
	customers(customer_name, customer_address)
VALUES
	('Miso Mishev', ('Dondukov', 'Sofia', '1000'));


SELECT 
	(customer_address).street,
	(customer_address).postal_code
FROM 
	customers;


	

